---
base_url: https://contactspec.org
title: ContactSpec
description: A proposal for sharing contact details as a vCard at /.well-known/contact.vcf.
brand: contactspec
cover: /img/socialspec-contact-cover.png

byline:
    name: ContactSpec
    favicon: /img/socialspec.png
    email: contact@socialspec.org
    href: /

links:
  - rel: icon
    href: /img/socialspec.png?v=1
    type: image/png
  - rel: me
    href: https://github.com/socialspec
  - rel: me
    href: https://github.com/socialspec/contactspec.org
  - rel: following
    href: /.well-known/following.opml

config:
    themes_dir: themes
    theme: themes/SocialSpec/0.1.1/theme.json
    status_layout: builtin/status.html
    status_redirect: /
    tidy_mode: true
    preview:
        id: contactspec-local
        bind: localhost
        port: 4176

providers:
    default:
        kind: s3
        endpoint: https://5a8b6c901ff20ee02892cf121b1ead54.r2.cloudflarestorage.com
        base_url: https://contactspec.org
        config:
            bucket: contactspec-production
            conditional_mode: etag
        secrets:
          - name: access_key_id
            key: AWS_ACCESS_KEY_ID
          - name: secret_access_key
            key: AWS_SECRET_ACCESS_KEY

environments:
    default: [default]

sync:
    remote: https://contactspec.org
